### PR TITLE
Utilize DOMPurify hooks to preserve <use> elements in playground mode

### LINKED ISSUE #155: <use> tag doesn't work in playground
**Describe the bug**
`DOMPurify` is used to sanitize all input text in playground, and by default it filters [`<use>`](https://www.w3.org/TR/SVG2/struct.html#UseElement) elements out, so in both SVG and PDF outputs they are not visible. Also it leads to `<use>` elements not preserved in playground url. 

One possible solution will be to use workaround provided by `DOMPurify` developers [here](https://github.com/cure53/DOMPurify/issues/233), it will allow to safely use internal references. It can be placed here: https://github.com/yWorks/svg2pdf.js/blob/929a2ba18bd55fa04bc012da9b5f6c8646a79c7d/playground/index.js#L28

**To Reproduce**
Check this code in playground:
```svg
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="200" height="100" viewBox="0 0 200 100">
  <title>Style inheritance and the use element</title>
  <style type="text/css">
    use { fill: orange; }
  </style>
  <g class="special" style="fill: blue">
     <circle id="c" cy="50" cx="50" r="40" />
  </g>
  <use xlink:href="#c" x="100" />
</svg>
```

**Screenshot**
Note: I changed height of input and output boxes in chrome devtools, so that it takes less space in screenshot.
image

**Expected behavior**
Example from above should result in two circles output (blue and orange), like in this [codepen](https://codepen.io/listopadiya/pen/YzWKKOE).

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 10.0.18363 Build 18363
 - Browser: Chrome 85.0.4183.121

### PR DESCRIPTION
**Pull request by listopadiya**
Closes #155. 

`<use>` tags were filtered out after sanitization, but with DOMPurify hooks this problem can be solved (regular expression still filter out links to external resources in the interest of security).

Can be checked in playground with following SVG code:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100" viewBox="0 0 200 100">
  <style type="text/css">
    use { fill: orange; }
  </style>
  <g class="special" style="fill: blue">
    <g id="face">
      <circle cx="50" cy="50" r="40" stroke="#000000" />
      <circle cx="30" cy="40" r="5" fill="#000000" />
      <circle cx="70" cy="40" r="5" fill="#000000" />
      <path
        fill="none"
        stroke="#000000"
        stroke-width="3"
        stroke-linecap="round"
        d="M30,60 C30,80 70,80 70,60" />
    </g>
  </g>
  <use xlink:href="#face" x="100" />
</svg>
```

**Before PR**
image

**After PR**
image

### CODE REVIEW

File: playground/index.js [hunk 1]
```diff
@@ -1,6 +1,12 @@
 const { jsPDF } = window.jspdf
 const DOMPurify = window.DOMPurify
 
+DOMPurify.addHook('afterSanitizeAttributes', node => {
+  if(node.hasAttribute('xlink:href') && !node.getAttribute('xlink:href').match(/^#/)) {
```
Comment (HackbrettXXX) [inline playground/index.js:5]: We should also check the `href` attribute without the `xlink` namespace.

**Review by HackbrettXXX — CHANGES_REQUESTED** [review]
Thanks for the PR :)

File: playground/index.js (hunk 1 above)
Comment (listopadiya) [reply playground/index.js]: Good point, I didn't know that it is deprecated in SVG 2. I have amended the commit and also added `playground` to prettier check.

File: package.json [hunk 2]
```diff
@@ -25,7 +25,7 @@
     "test-typescript": "karma start ./test/deployment/typescript/karma.conf.js",
     "test:ci": "cross-env SHOW_DIFF=true npm run test",
     "createreferences": "node test/common/reference-server.js",
-    "prettier": "prettier --write {src,tests,typings}/**/*.{ts,js}",
+    "prettier": "prettier --write {playground,src,tests,typings}/**/*.{ts,js}",
     "lint": "eslint {src,tests,typings}/**/*.{ts,js}"
```
Comment (HackbrettXXX) [inline package.json:29]: Sorry for nitpicking, but we should also add it to the `lint` task then.

**Review by HackbrettXXX — CHANGES_REQUESTED** [review]

File: package.json (hunk 2 above)
Comment (listopadiya) [reply package.json]: Makes sense, I updated that 👌

**Review by HackbrettXXX — APPROVED** [review]
Alright. Thanks for the PR :)
